version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
